### ISSUE TITLE
action_count misaligns over time

### ISSUE THREAD

**Issue by one-some** [henk717/KoboldAI-Client#257]
Moved from the ui2 branch for visibility -- from what I know this is super common on any story longer than ~30-50 actions

Sometimes `action_count` gets misaligned, causing new actions to be inserted in unexpected places.

Of note:
- Of the 14 actions in my save, the 4th, 5th, 6th, 7th, 8th, 10th, and 14th were empty.
- The old UI is seemingly unaffected by this
- The bug can be forced by manually editing the `action_count` to be lower than it actually is
- Lots of retries and multi-level undos were made in my test before the issue showed up
- Seems to happen more often on longer stories

A user's detailed report:
>  I've seen it all 3 sessions I've used the new ui on colab. Specifically, it takes the latest generation and spits it out at somewhere that's not at the bottom. It is always between chunks, not in the middle of one, and has a heavy tendency to end up at the top, before the prompt (ends up there ~50% of the time, the other 50% being between any other chunk). It's easy to spot when it happens because when you submit, it ends loading but nothing has been added. And when you hit back, it "seems" like nothing is being removed (but it's actually removing that misplaced generation from somewhere else).
>
> Working around it is a huge pain, but maybe something from my observations can help identify it. Hitting back and generating again will put the misplaced generation back in the same wrong spot (but with new text). Editing the previous output/submission does not fix this; it still goes to the same wrong spot. Closing and reopening the browse tab (or refreshing) don't fix it. I've found two ways around it that sometimes work. 1, copy the misplaced generation, edit-delete it from the passage (not using the Back function), paste the input at the bottom, and pretend it never happened. 2, copy the latest generation before the misplaced one, delete the chunk, and paste it into the chunk before that one. Both of these methods have worked at temporarily fixing the problem, but I've also ended up in scenarios where there was no way forward but starting a new story and copy/pasting plain text of the old one into it to continue.
> I have no idea what triggers it, but it seems to happen once the story gets lengthy. Every time I've encountered it it has been after 20 to 40 generations. I also always start from a fresh new story, not swapping ui's or loading saves, so it's not related to those things.

**Comment by ebolam** [comment]
That's helpful. I'll see if I can recreate. Manually changing the action_count would cause problems (not sure exactly what) but that doesn't surprise me.

**Comment by ebolam** [comment]
For any reading this, it should be fixed in pull #272 (fingers crossed)
