### ISSUE TITLE
Verbose logging for GPU support

### ISSUE THREAD

**Issue by rsedxcftvgyhbujnkiqwe** [henk717/KoboldAI-Client#262]
I have been attempting to get the rocm version of kobold running on linux, but each time I do it says my GPU is not supported and switches to CPU only mode. I'm fairly sure I have ROCm installed correctly, but even if I don't I doubt any of the people who know about ROCm would be able to help with the kobold use case.
Is it possible to get some verbose logging on why exactly the GPU isn't supported? The console just displays the fact that it isn't supported, rather than why and what error is causing it. This would greatly improve the ability to debug problems and issues on local hosting. If such a feature exists, please let me know because it's not documented anywhere

**Comment by henk717** [comment]
I'm not sure if we can be more verbose about it, but it typically happens when no GPU is reported back by ROCm.
Usually a dependency error, or your GPU is not ROCm supported.
Have you tried rocminfo to see if it shows up there?

**Comment by rsedxcftvgyhbujnkiqwe** [comment]
I only tried rocm-smi, but I'll try rocminfo as well. Will report back later with results

**Comment by ebolam** [comment]
The simpliest way to see if it'd work is to check if pytorch sees it or not.
You can do a:
python
import torch
torch.cuda.is_available()

If you get True, you should be good to go. If you get False, then there is some problem with ROCm (or a problem between ROCm and pytorch) and pytorch doesn't see it

**Comment by henk717** [comment]
ROCm should be fixed now.
git pull && ./install_requirements.sh rocm

**Comment by rsedxcftvgyhbujnkiqwe** [comment]
> ROCm should be fixed now. git pull && ./install_requirements.sh rocm

Confirmed, latest release detects the GPU properly.
