### ISSUE TITLE
[Feature Request] Stream tokens character by character

### ISSUE THREAD

**Issue by SammCheese** [henk717/KoboldAI-Client#263]
As of right now, Tokens generated are displayed immediately if token streaming is enabled. This however can look rather choppy on slower generating devices.

To counteract this, I'm proposing a small change in the token streaming feature. Instead of showing the whole token immediately, show the characters one after another.

This change would provide a smoother and more consistent user experience, as well as creating the illusion of faster generations which is beneficial to everyone.

**Comment by ebolam** [comment]
So I don't forget or if someone else wants to work on this, we could have it type the word at a speed equal to the tqdm speed (seconds/token) and post the completed token if a new one comes in without waiting.
