### ISSUE TITLE
Webserver is willing and able to share its port on ubuntu 22.04

### ISSUE THREAD

**Issue by BullyNextDoor** [henk717/KoboldAI-Client#278]
I was able to start two instances of koboldai on one machine, and they happily shared port 5000.

While this is interesting behavior, it completely messed up the UI (both United and base).

To reproduce, simply start KAI. Then open another terminal and start another KAI. Then browse to localhost:5000 and try.

**Comment by henk717** [comment]
Amusing results, but I don't consider this a bug inside KoboldAI itself if the OS does not block the port.
The fix is simply not running two instances on the same port. Coding an entire port checking routine just to avoid this kind of user / os error would be a bit much in my opinion.
