### ISSUE TITLE
New UI - Formatting Option - API Bug

### ISSUE THREAD

**Issue by alicat22** [henk717/KoboldAI-Client#290]
Kobold New UI
https://gyazo.com/c715b80b216cd194687a0f4fe321b702

When Trim Sentences, No Special Chars, Single Line, No Blank Lines, Auto Spacing, or No Special Chars are enabled and you generate through the API to TavernAI, the buttons will flick on and off.

The following Formatting options don't appear to be working properly, as well:
Trim Sentences - Doesn't work properly. [See debug log](https://gist.github.com/cass02/828be6335df08b634467c74b2f74b9d4#file-kobold_debug-trim)
Single Line - Doesn't work properly. [See debug log](https://gist.github.com/cass02/828be6335df08b634467c74b2f74b9d4#file-kobold_debug-single-line)
No Blank Lines - Doesn't work properly. [See debug log](https://gist.github.com/cass02/828be6335df08b634467c74b2f74b9d4#file-kobold_debug-blank-lines)

Windows 10: 10.0.19045 Build 19045
Running Local
Model: pygmalion-6b
KoboldAI Version: [cc01ad7](https://github.com/KoboldAI/KoboldAI-Client/commit/cc01ad730ae428c64202220ac5cd141a501ad677)

I can send any additional logs, just let me know!

**Comment by henk717** [comment]
The interface mimicks what the API is currently requesting since the API will adjust the settings. That is expected behavior.
The formatting options currently do not apply to the API, API generations are always raw.
