### ISSUE TITLE
TypeError: set_module_tensor_to_device() takes from 3 to 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by GoAwayNow** [henk717/KoboldAI-Client#329]
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/kaggle/tmp/KoboldAI/aiserver.py", line 3227, in load_model
    move_model_to_devices(model)
  File "/kaggle/tmp/KoboldAI/aiserver.py", line 1131, in move_model_to_devices
    accelerate.utils.set_module_tensor_to_device(model, key, torch.device(value.device), value, target_dtype)
TypeError: set_module_tensor_to_device() takes from 3 to 4 positional arguments but 5 were given
```

This occurs when trying to run aiserver.py.

I'm running it as follows: `python /kaggle/tmp/KoboldAI/aiserver.py  --model PygmalionAI/pygmalion-6b --quiet --breakmodel_gpulayers 14,14`

I'm using Kaggle, but several users on Reddit have also encountered this error, at least one on their personal computer.
https://www.reddit.com/r/PygmalionAI/comments/12a1sig/help/

A user in the thread traced says the issue started with 4a8b099. I haven't used it in a few weeks, so I can't personally speak to when it first occurred.

**Comment by henk717** [comment]
This is a dependency issue, Kaggle apparently ships with a version of Accelerate that is to old.
I have added the version pin to the requirements.txt to help solve that.
