### ISSUE TITLE
Hello, I have a problem with "AI automatically deletes generated content at the end of each content generation".

### ISSUE THREAD

**Issue by anyezhixie** [henk717/KoboldAI-Client#372]
What I have observed so far is that when using models like HyperMantis and Chronos, it will delete all but the first paragraph of the current output after each generation.
When using Erebus and Hermes, it will most likely delete all the content generated this time.
If I switch to the new UI, all the content generated by the latter will probably be saved, but it will not be possible to go backwards, only the commands and actions I entered will be reverted, but not the AI output.
I tried reinstalling KAI to reset the settings, but it still didn't work, here's a screenshot of what I did with the UI and server when this happened.
https://imgloc.com/i/VlgByq
https://imgloc.com/i/VlgXIz
But given that I am currently using KAI from the 4bit branch, if the issue has been fixed in the current update, could someone in the know please tell me what file I should download to fix the issue and ensure that the 4bit version is not broken?

**Comment by henk717** [comment]
You likely have trim incomplete sentences active in the formatting options. Or if the new UI was used its possible you have a desync issue. If you can reproduce a scenario on this github's branch where UI1 and UI2 are not in sync let us know how to reproduce this.

UI desync issues with the 4bit branch we do not support since its two months old.

**Comment by anyezhixie** [comment]
> You likely have trim incomplete sentences active in the formatting options. Or if the new UI was used its possible you have a desync issue. If you can reproduce a scenario on this github's branch where UI1 and UI2 are not in sync let us know how to reproduce this.
> 
> UI desync issues with the 4bit branch we do not support since its two months old.

Thank you for your reply, your last reply also solved the problem for me. But this time, when I turn off all the options in "Formatting", it still happens that the AI deletes all the contents of this output. Is it possible that there is some kind of bug that causes the default "Formatting" option to be turned on when the UI is running in the backend, even if the frontend manually stops the option?

**Comment by anyezhixie** [comment]
> You likely have trim incomplete sentences active in the formatting options. Or if the new UI was used its possible you have a desync issue. If you can reproduce a scenario on this github's branch where UI1 and UI2 are not in sync let us know how to reproduce this.
> 
> UI desync issues with the 4bit branch we do not support since its two months old.

Hello, I may be closer to locating the exact source of this error in my further attempts.
I found that the problem only occurs when adventure mode is checked, the sentence clipping of the AI in normal and chat mode works fine, indicating that the problem should be in the button for adventure mode in the settings?
I know I'm asking too much, but I hope you'll take a look at this if you have a spare moment, thanks a lot and sorry for the trouble I've caused.

**Comment by anyezhixie** [comment]
I seem to understand why "adventure mode" causes the AI to generate short statements or delete a lot of generated content.
There should be a built-in trim command that cannot be turned off, which actively deletes all but the first paragraph of the generated content.
I guess its purpose is to limit the randomness of the AI, so that the AI does not generate a lot of plot beyond the content of the player's instructions.
But most of the new models are not currently trained or tuned specifically for the KAI's adventure mode, which results in output formats that may directly conflict with the command, such as their first paragraph being a "space".
