### ISSUE TITLE
No module named progressbar

### ISSUE THREAD

**Issue by DanZinagri** [henk717/KoboldAI-Client#375]
Getting the following trying to load any model:

`KoboldAI/tpu_mtj_backend.py", line 35, in <module>
    import progressbar

ModuleNotFoundError: No module named 'progressbar'
`

This happened after the most recent git pull. I tried a fresh install alongside install_requiremens.sh being run; tried setting up a venv within the koboldAI folder to install the progressbar module;  alongside attempting to manually run the requirements.txt (though that resulted in a error installing lupa)

**Comment by henk717** [comment]
Make sure your not accidentally using the Huggingface MTJ backend, we do not yet have the detection in place that hides it from local users.

**Comment by DanZinagri** [comment]
How would i go about checking that? is it just looking for a package under the pip list? I don't see anything with mtj or huggingface in the name.
To my knowledge just about most everything from the stablediffusion install was in its own separate venv as my system will give me a "this environment is externally managed" error if i attempt to do so otherwise. And i don't think anything from the stablediffusion isntall ran --break-system-packages to install something like that system-wide

**Comment by YellowRoseCx** [comment]
> How would i go about checking that? is it just looking for a package under the pip list? I don't see anything with mtj or huggingface in the name. To my knowledge just about most everything from the stablediffusion install was in its own separate venv as my system will give me a "this environment is externally managed" error if i attempt to do so otherwise. And i don't think anything from the stablediffusion isntall ran --break-system-packages to install something like that system-wide

What is the workflow you did to install and run KoboldAI?
```
git clone https://github.com/henk717/KoboldAI
cd KoboldAI
./install_requirements.sh cuda
./play.sh
```
?

**Comment by DanZinagri** [comment]
yep that was the exact steps i took

**Comment by DanZinagri** [comment]
(accidentally hit close).

Just for good measure i just nuked the install and did it again for the 4th time now. This worked about 2-3 weeks ago when i last was trying to use it.

After that i just attempt to load a model.
For example just clicking AI, then adventure, then Adventure 2.7B

`INFO       | modeling.inference_models.hf:set_input_parameters:191 - {'class': 'model', 'label': 'Adventure 2.7B', 'id': 'KoboldAI/GPT-Neo-2.7B-AID', 'name': 'KoboldAI/GPT-Neo-2.7B-AID', 'size': '8GB', 'ismenu': 'false', 'isdownloaded': 'false', 'isdirectory': 'false', 'menu': 'adventurelist', 'plugin': 'Huggingface MTJ'}
INIT       | Searching  | GPU support
INIT       | Found      | GPU support
ERROR      | __main__:g:658 - An error has been caught in function 'g', process 'MainProcess' (86057), thread 'MainThread' (139980806876032):
Traceback (most recent call last):
`

I've tried this across multiple models/categories.

Its something that changed in this version, because if i do the https://github.com/KoboldAI/KoboldAI-Client.git (separate download/directory keeping them separate) it works fine. But without all the nice fancy UI improvements and-so-on

**Comment by henk717** [comment]
As mentioned before its the fact it chose the Huggingface MTJ backend instead of the correct one, you can manually select Huggingface from the drop-down or update to the latest version of KoboldAI United.

In the newer version of KoboldAI United we check if you have the correct dependencies for the TPU, and if not we hide the MTJ backend entirely so local users no longer see it.
