### ISSUE TITLE
[BUG] Stuck like this for the past 2 hours

### ISSUE THREAD

**Issue by ttt845h** [henk717/KoboldAI-Client#380]
Updating to the latest KoboldAI United for full support
If you like a different version run the updater again once the update is complete
Reinitialized existing Git repository in C:/KoboldAI/.git/
Fetching origin
remote: Enumerating objects: 792, done.
remote: Counting objects: 100% (451/451), done.
remote: Compressing objects: 100% (128/128), done.
remote: Total 792 (delta 350), reused 380 (delta 310), pack-reused 341
Receiving objects: 100% (792/792), 898.41 KiB | 2.53 MiB/s, done.
Resolving deltas: 100% (516/516), completed with 14 local objects.
From https://github.com/henk717/koboldai
 * [new branch]      united            -> origin/united
 * [new tag]         Snapshot-7-5-2023 -> Snapshot-7-5-2023
Fetching submodule KoboldAI-Horde-Bridge
From https://github.com/db0/KoboldAI-Horde-Bridge
   d9014eb..20e8701  master     -> origin/master
Already on 'united'
'origin' is not recognized as an internal or external command,
operable program or batch file.
Fetching origin
Already on 'united'
HEAD is now at b5bdb1d Merge pull request #377 from ebolam/Model_Plugins
'branch' is not recognized as an internal or external command,
operable program or batch file.
Reinitialized existing Git repository in C:/KoboldAI/.git/
Fetching origin
From https://github.com/henk717/koboldai
 * [new branch]      united     -> origin/united
Already on 'united'
HEAD is now at b5bdb1d Merge pull request #377 from ebolam/Model_Plugins
Submodule path 'KoboldAI-Horde-Bridge': checked out '20e8701dd27d478ff405f4ac6e2042edf06174df'

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

nvidia/noarch                                        4.4kB @   6.6kB/s  0.7s
pytorch/noarch                                      10.2kB @  15.0kB/s  0.7s
pytorch/win-64                                     125.0kB @ 173.9kB/s  0.7s
nvidia/win-64                                       93.5kB @ 128.6kB/s  0.7s
pkgs/msys2/win-64                                   39.8kB @  36.8kB/s  0.4s
pkgs/r/noarch                                        1.3MB @ 795.9kB/s  1.0s
pkgs/main/noarch                                   850.6kB @ 454.5kB/s  0.8s
pkgs/msys2/noarch                                  111.0 B @  55.0 B/s  0.1s
pkgs/r/win-64                                      742.8kB @ 360.8kB/s  0.4s
pkgs/main/win-64                                     5.2MB @   1.8MB/s  2.4s
conda-forge/noarch                                  13.1MB @   3.6MB/s  3.5s
[+] 55.9s
conda-forge/win-64 -----------------------------------------------------------------   1.7MB /  ??.?MB @  29.7kB/s 55.9s

**Comment by henk717** [comment]
This is up to your own download connection to the anaconda servers, not much we can do.
You can try to use a VPN such as Cloudflare Warp to see if that helps your internets stability on the download.

**Comment by ttt845h** [comment]
oh and each time i run the clone command in models and wait for a bit my pc bluescreens
