### ISSUE TITLE
In chat mode, after the answer, the empty space is filled with random words and symbols.

### ISSUE THREAD

**Issue by Nourepide** [henk717/KoboldAI-Client#396]
I use united version on Google Collab (TPU) with [WizardLM-13B](https://huggingface.co/WizardLM/WizardLM-13B-V1.1).

After bot answer I often get a sequence of random words or symbols. Like that:
![image](https://github.com/henk717/KoboldAI/assets/22074527/c1ac348c-f1b2-43db-9406-ca297ff7993a)

In current situation I just got a "Java imports" and it can still be explained, but more often I get absolutely absurdus sequences.

![image](https://github.com/henk717/KoboldAI/assets/22074527/72ef869e-9df8-4ffd-b66d-bde97c91d2a4)

At first glance it seems that the problem is in the model, but I don't get that problem in story or adventure mode.

It looks like after a normal response, the model is forced to fill the remaining space with any tokens up to the specified value in "Output Length".

I tried to change any settings, including sampler, formatting, repetition, and others. However, the only thing that can change this is the "Output length" and then it only changes the amount of nonsense that I will receive in the chat.

As a result, I have to use adventure mode as chat mode and it's not very convenient. 😅

**Comment by henk717** [comment]
This is something the model decided to do, the TPU implementation of llama is more limited so we do not have our usual tricks in place that aid in keeping things on track. I recommend trying a different model that is less prone to this.

**Comment by Nourepide** [comment]
But then why doesn't it show up in adventure or story mode?

![image](https://github.com/henk717/KoboldAI/assets/22074527/377c6da3-32ba-4987-a515-9f3cdd28cec7)

And can I modify template for adventure mode like turn_template in [oobabooga](https://github.com/oobabooga/text-generation-webui/blob/main/characters/instruction-following/Alpaca.yaml)?

**Comment by henk717** [comment]
Probably because the model is less sensitive to its formatting. There is no templates for adventure mode, we do however have an actual instruct mode in KoboldAI Lite that might be able to assist you. You can access it by adding /lite to the URL. If your using an outdated fork you can alternatively use https://lite.koboldai.net and hook that up to your KoboldAI instance with the Custom Remote Endpoint option in the AI menu.

**Comment by Nourepide** [comment]
Okay. Thanks a lot for the answers.
It's a pity that there is a limitation on the TPU version, but it's better than nothing.

**Comment by Nourepide** [comment]
Looks like a lite version has no this behavior
![image](https://github.com/henk717/KoboldAI/assets/22074527/7f5ed80d-881a-4d4f-b346-f037dc43b7e0)
