### ISSUE TITLE
Streaming does not work with sillytavern

### ISSUE THREAD

**Issue by christiandaley** [henk717/KoboldAI-Client#427]
I have "token streaming" enabled but when connected to the api with sillytavern I get this error when trying to generate a response:
![image](https://github.com/henk717/KoboldAI/assets/5554082/34eaf603-62be-462a-a79d-e1538eae1bab)

Streaming to sillytavern does work with koboldcpp

Edit: I've noticed that even though I have "token streaming" on, when I make a request to the api the token streaming field automatically switches back to off.

**Comment by henk717** [comment]
Currently not supported, once we have a streaming API for KoboldAI sillytavern will need to be updated for it.
Koboldcpp uses an unofficial extention to our API to get it earlier than us.
