### ISSUE TITLE
How do I get my GPU to stop disconnecting?

### ISSUE THREAD

**Issue by Astroxxoo** [henk717/KoboldAI-Client#443]
I keep having to redo my KoboldAI download because it says my GPU disconnected this happens every 15-30 so minutes before I have to redownload it

**Comment by henk717** [comment]
Assuming this is colab make sure the tab isn't getting suspended by playing the audio player for mobile users (Some desktop browsers began suspending them to).

Alao make sure you don't miss any of the captchas they display or they shut you down.

We dont have control over this ourselves.
