### ISSUE TITLE
Bug:  KOBOLDAI_ARGS not implemented (docker)

### ISSUE THREAD

**Issue by chrisbennight** [henk717/KoboldAI-Client#485]
https://github.com/henk717/KoboldAI/blob/united/docker-standalone/Readme.txt#L17
Indicates that KOBOLDAI_ARGS will override the default args, but this doesn't seem to be implemented

-- https://github.com/KoboldAI/KoboldAI-Client/blob/main/docker-standalone/docker-helper.sh#L47 - no logic here
-- https://github.com/search?q=repo%3AKoboldAI%2FKoboldAI-Client%20KOBOLDAI_ARGS&type=code - search shows only ref to that env var as in the docs

So unless I'm missing something there is no way to override the args in the docker image?

(my specific problem is I want to disable the cloudflare tunnel; --host instead of --remote, and I was unable to change the default behaviour with that env var)

**Comment by henk717** [comment]
It definately works since I also use it in my runpod template over at https://koboldai.org/runpod-united
You are looking for this https://github.com/henk717/KoboldAI/blob/united/aiserver.py#L1496-L1499

**Comment by chrisbennight** [comment]
Ah, I thought "latest" was the docker tag to use, not "united".  From your code ref  I see the logic in the united branch
(and at https://hub.docker.com/r/koboldai/koboldai/tags I see latest is 6 months older than united)
