### ISSUE TITLE
 libmamba Package cache error

### ISSUE THREAD

**Issue by SusieDreemurr** [henk717/KoboldAI-Client#494]
I got this error while installing Kobold on Linux Mint. I have an AMD card and ran the play-rocm.sh script when I received this at the end of the installation. I don't know what it means.

![Screenshot from 2023-12-19 10-44-42](https://github.com/henk717/KoboldAI/assets/136935928/6a80f79b-e7ed-47be-85c9-1ec1094769d3)

**Comment by henk717** [comment]
This is currently an upstream issue with conda that began yesterday.  You can bypass the issue by removing ffmpeg from rocm.yaml

**Comment by SusieDreemurr** [comment]
> This is currently an upstream issue with conda that began yesterday. You can bypass the issue by removing ffmpeg from rocm.yaml

I tried it. For some reason it caused my CPU to shoot way up. I had to boot the installation process.

**Comment by henk717** [comment]
The latest commit fixes the issue by restoring the old micromamba. CPU usage is out of our control but its back to the known good version.
